### ISSUE TITLE
Module not found: Can't resolve 'umi/locale' 

### ISSUE THREAD

**Issue by XUHAOLIANG2014** [umijs/umi-plugin-locale#5]
antd pro中，使用npm install umi-plugin-locale --save-dev安装完毕后，启动报Module not found: Can't resolve 'umi/locale' 。请问是什么原因？

**Comment by XUHAOLIANG2014** [comment]
原来是路径不对。。。。import的时候不是UMI

**Comment by XUHAOLIANG2014** [comment]
HI 
      按照例子，建了local目录及中文的zh-CN.js.但是以下getlocale()返回是zh-CN，但是获取id：test的返回值就null.麻烦看看可能是哪里没有设定好吗？
console.log(getLocale(), formatMessage({
      id: 'test'
    }, {
      name: 'antd'
    }));

**Comment by yutingzhao1991** [comment]
@XUHAOLIANG2014 使用 umi-plugin-locale 的前提是用了 umi。
